### ISSUE TITLE
Persistence between executions?

### ISSUE THREAD

**Issue by taybin** [vfarcic/docker-flow-cron#19]
Does df-cron store the services it adds?  I'm wondering if it needs the services re-added to it if it crashes.

Or if it's listening for new services, does it check for existing services with the appropriate labels on startup?  It'd be neat if it could store whether it had already seen a service, had crashed, and then on launch realized it missed the timeframe to run it, so then run it immediately.

I think some sort of persistence layer would help give some guarantees about the robustness of the cron service.

**Comment by d-h1** [comment]
It does not store all scheduled services but instead reschedules them on startup by adding all services with the label ```com.df.cron.name``` to df-cron again... Please let me know if this doesn't work as expected and we can reopen the issue.
